### ISSUE TITLE
the step fails on installing a dependency

### ISSUE THREAD

**Issue by lindseybateman** [wercker/wercker-step-hipchat-notify#10]
```
wercker_step_hipchat_notify: WARN: Installing missing packages 'sudo gawk'
wercker_step_hipchat_notify: FAIL: Essential dependency 'sudo' not found on the PATH (with arguments '-p
```

**Comment by drissamri** [comment]
Same issue here. 

```
  after-steps:
    - hipchat-notify:
        token: $HIPCHAT_TOKEN
        room-id: $HIPCHAT_ROOM
```

**Comment by nhuray** [comment]
Exactly the same issue :(

**Comment by nhuray** [comment]
The way I fix it : 

```
    after-steps:
        - script:
            name: Install dependencies
            code: |
               apt-get update && apt-get install -y sudo gawk

        - hipchat-notify:
            from-name: Wercker
            token: "$HIPCHAT_TOKEN"
            room-id: "$HIPCHAT_ROOM"
            message-format: html
```

But it's just a workaround !
