### ISSUE TITLE
from-name AND api key label both not working with api v2

### ISSUE THREAD

**Issue by ifightcrime** [wercker/wercker-step-hipchat-notify#11]
I've tried `from-name` in wercker.yml and setting my v2 api token label, but the from name is still being set as my own name.

```
    after-steps:
        - hipchat-notify:
            token: $HIPCHAT_TOKEN
            room-id: 111111
            from-name: Wercker
```
