### ISSUE TITLE
Events always post on HipChat

### ISSUE THREAD

**Issue by codisms** [wercker/wercker-step-hipchat-notify#13]
Despite setting notifications to failed only, all build messages are passing to HipChat. It appears that the "on" setting isn't working.

Configuration:
```
    - hipchat-notify:
        token: $HIPCHAT_TOKEN
        room-id: 7xxxx0
        from-name: wercker
        on: failed
```
