### ISSUE TITLE
wercker_step_hipchat_notify: FAIL: WERCKER_STARTED_BY is not set

### ISSUE THREAD

**Issue by giovannicandido** [wercker/wercker-step-hipchat-notify#16]
Trying to use the plugin result in this error:

```
  after-steps:
    - hipchat-notify:
      token: $HIPCHAT_TOKEN
      room-id: $HIPCHAT_ROOM_ID
```
